import copy

CORE_SKELETON = [
    {
        "id": "TASK-PARSE",
        "title": "Parse Specification",
        "objective": "Extract structured requirements from the input specification",
        "description": "Analyse the raw spec and produce a normalised requirements bundle",
        "phase": "parse_spec",
        "parent_id": None,
        "group": "analysis",
        "execution_type": "atomic",
        "type": "design",
        "tags": ["spec", "parse"],
        "deps": [],
        "agent_type": "Spec Analyst",
        "required_inputs": ["raw_spec"],
        "expected_outputs": ["spec_bundle"],
        "done_definition": "spec_bundle produced and validated",
        "verification_steps": ["spec_bundle schema check"],
        "priority": "high",
        "risk_level": "low",
        "enriched_by": "skeleton",
        "llm_enriched": False,
        "created_by_rule": None,
    },
    {
        "id": "TASK-DESIGN",
        "title": "Design Solution",
        "objective": "Produce a high-level solution design from the parsed spec",
        "description": "Translate requirements into an architectural and component design",
        "phase": "design_solution",
        "parent_id": None,
        "group": "design",
        "execution_type": "atomic",
        "type": "design",
        "tags": ["design", "architecture"],
        "deps": ["TASK-PARSE"],
        "agent_type": "Solution Architect",
        "required_inputs": ["spec_bundle"],
        "expected_outputs": ["design_doc"],
        "done_definition": "design_doc produced and reviewed",
        "verification_steps": ["design_doc schema check"],
        "priority": "high",
        "risk_level": "medium",
        "enriched_by": "skeleton",
        "llm_enriched": False,
        "created_by_rule": None,
    },
    {
        "id": "TASK-IMPL",
        "title": "Implement",
        "objective": "Implement the solution according to the design",
        "description": "Write code and tests to fulfil the design specification",
        "phase": "implement",
        "parent_id": None,
        "group": "implementation",
        "execution_type": "atomic",
        "type": "coding",
        "tags": ["implementation", "code"],
        "deps": ["TASK-DESIGN"],
        "agent_type": "Developer",
        "required_inputs": ["design_doc"],
        "expected_outputs": ["implementation", "unit_tests"],
        "done_definition": "all unit tests pass, code reviewed",
        "verification_steps": ["run unit tests", "lint check"],
        "priority": "high",
        "risk_level": "medium",
        "enriched_by": "skeleton",
        "llm_enriched": False,
        "created_by_rule": None,
    },
    {
        "id": "TASK-VALIDATE",
        "title": "Validate",
        "objective": "Validate that the implementation meets the original requirements",
        "description": "Run acceptance tests and verify outputs against spec",
        "phase": "validate",
        "parent_id": None,
        "group": "quality",
        "execution_type": "atomic",
        "type": "testing",
        "tags": ["validation", "qa"],
        "deps": ["TASK-IMPL"],
        "agent_type": "QA Engineer",
        "required_inputs": ["implementation", "spec_bundle"],
        "expected_outputs": ["validation_report"],
        "done_definition": "validation_report produced, all checks pass",
        "verification_steps": ["run acceptance tests", "check validation_report"],
        "priority": "high",
        "risk_level": "low",
        "enriched_by": "skeleton",
        "llm_enriched": False,
        "created_by_rule": None,
    },
]


def build_skeleton():
    """Return a deep copy of the core 4-phase task skeleton."""
    return copy.deepcopy(CORE_SKELETON)
