from typing import Protocol


class GateIO(Protocol):
    def present(self, brief: dict) -> None: ...
    def collect_edit(self, brief: dict) -> dict: ...
    def confirm(self, brief: dict) -> bool: ...
